# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param y A arma::vector of outcomes.
#' @param X A arma::matrix of spline bases.
#' @param alpha.schedule The prior on lambda
#' @export
NULL

bayesLasso <- function(y, X, alpha, tol) {
    .Call(`_NithinPackage_bayesLasso`, y, X, alpha, tol)
}

setupGCV <- function(y, X, alphas) {
    .Call(`_NithinPackage_setupGCV`, y, X, alphas)
}

update <- function(L, tol) {
    .Call(`_NithinPackage_update`, L, tol)
}

GCV <- function(y, X, alphas, tol) {
    .Call(`_NithinPackage_GCV`, y, X, alphas, tol)
}

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param y A vector of outcomes.
#' @param X A matrix of spline bases.
#' @param alpha.schedule The prior on lambda
#' @export
NULL

myrank <- function(x) {
    .Call(`_NithinPackage_myrank`, x)
}

checkcor <- function(cors, thresh) {
    .Call(`_NithinPackage_checkcor`, cors, thresh)
}

subSamp <- function(v) {
    .Call(`_NithinPackage_subSamp`, v)
}

namesAndCorrs <- function(XSubsamp, Xnames, ySubsamp, colSizes, treatSubsamp, XConstruct, treatConstruct, treatNames, a) {
    .Call(`_NithinPackage_namesAndCorrs`, XSubsamp, Xnames, ySubsamp, colSizes, treatSubsamp, XConstruct, treatConstruct, treatNames, a)
}

checkcor <- function(cors, thresh) {
    .Call(`_NithinPackage_checkcor`, cors, thresh)
}

splineCorrs <- function(XSubsamp, ySubsamp, treatSubsamp, XConstruct, treatConstruct, a) {
    .Call(`_NithinPackage_splineCorrs`, XSubsamp, ySubsamp, treatSubsamp, XConstruct, treatConstruct, a)
}

