# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param y A arma::vector of outcomes.
#' @param X A arma::matrix of spline bases.
#' @param alpha.schedule The prior on lambda
#' @export
NULL

bayesLasso <- function(y, X, alpha, tol) {
    .Call(`_NithinPackage_bayesLasso`, y, X, alpha, tol)
}

updateEtausqinv <- function(y, X, alpha, Etausqinv, tol) {
    .Call(`_NithinPackage_updateEtausqinv`, y, X, alpha, Etausqinv, tol)
}

GCV <- function(y, X, alphas, tol) {
    .Call(`_NithinPackage_GCV`, y, X, alphas, tol)
}

#' Check Spearman correlations between interactions in X and treatment
#' 
#' @param y A vector of outcomes.
#' @param X A matrix of spline bases.
#' @param alpha.schedule The prior on lambda
#' @export
NULL

bs2 <- function(x, deg) {
    .Call(`_NithinPackage_bs2`, x, deg)
}

dbs2 <- function(x, deg) {
    .Call(`_NithinPackage_dbs2`, x, deg)
}

bsme <- function(x) {
    .Call(`_NithinPackage_bsme`, x)
}

dbsme <- function(x) {
    .Call(`_NithinPackage_dbsme`, x)
}

makebs <- function(X) {
    .Call(`_NithinPackage_makebs`, X)
}

splineBases <- function(X, covs) {
    .Call(`_NithinPackage_splineBases`, X, covs)
}

subSamp <- function(v) {
    .Call(`_NithinPackage_subSamp`, v)
}

splineBasesAndCorrs <- function(obs, covs, X, Xname, y, treat, treatName, a) {
    .Call(`_NithinPackage_splineBasesAndCorrs`, obs, covs, X, Xname, y, treat, treatName, a)
}

checkcor <- function(cors, thresh) {
    .Call(`_NithinPackage_checkcor`, cors, thresh)
}

main <- function() {
    .Call(`_NithinPackage_main`)
}

